# Getting started

Once you've chosen your scenario, download the data from [the Iowa website](https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy) in csv format. Start by loading the data with pandas. You may need to parse the date columns appropriately.

In [2]:
import pandas as pd

## Load the data into a DataFrame
df = pd.read_csv('../starter-code/data/Iowa_Liquor_sales_sample_10pct.csv')

## Transform the dates if needed, e.g.
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")

df['Date'].describe()
#df['County Number'] = int(df['County Number'])

for x in df.columns:
    print "Column", x
    print df[x].describe()
    print

print df.columns
print df.dtypes

Column Date
count                  270955
unique                    274
top       2015-12-01 00:00:00
freq                     1555
first     2015-01-05 00:00:00
last      2016-03-31 00:00:00
Name: Date, dtype: object

Column Store Number
count    270955.000000
mean       3590.263701
std         947.662050
min        2106.000000
25%        2604.000000
50%        3722.000000
75%        4378.000000
max        9023.000000
Name: Store Number, dtype: float64

Column City
count         270955
unique           385
top       DES MOINES
freq           23724
Name: City, dtype: object

Column Zip Code
count     270955
unique       415
top        50010
freq        7091
Name: Zip Code, dtype: object

Column County Number
count    269878.000000
mean         57.231642
std          27.341205
min           1.000000
25%          31.000000
50%          62.000000
75%          77.000000
max          99.000000
Name: County Number, dtype: float64

Column County
count     269878
unique        99
top         Polk
freq       49102
Name: County, dtype: object

Column Category
count    2.708870e+05
mean     1.043888e+06
std      5.018211e+04
min      1.011100e+06
25%      1.012200e+06
50%      1.031200e+06
75%      1.062310e+06
max      1.701100e+06
Name: Category, dtype: float64

Column Category Name
count             270323
unique                71
top       VODKA 80 PROOF
freq               35373
Name: Category Name, dtype: object

Column Vendor Number
count    270955.00000
mean        256.43443
std         141.01489
min          10.00000
25%         115.00000
50%         260.00000
75%         380.00000
max         978.00000
Name: Vendor Number, dtype: float64

Column Item Number
count    270955.000000
mean      45974.963300
std       52757.043086
min         168.000000
25%       26827.000000
50%       38176.000000
75%       64573.000000
max      995507.000000
Name: Item Number, dtype: float64

Column Item Description
count           270955
unique            2173
top       Black Velvet
freq              7233
Name: Item Description, dtype: object

Column Bottle Volume (ml)
count    270955.000000
mean        924.830341
std         493.088489
min          50.000000
25%         750.000000
50%         750.000000
75%        1000.000000
max        6000.000000
Name: Bottle Volume (ml), dtype: float64

Column State Bottle Cost
count     270955
unique      1086
top        $8.25
freq        6160
Name: State Bottle Cost, dtype: object

Column State Bottle Retail
count     270955
unique      1112
top       $12.38
freq        6160
Name: State Bottle Retail, dtype: object

Column Bottles Sold
count    270955.000000
mean          9.871285
std          24.040912
min           1.000000
25%           2.000000
50%           6.000000
75%          12.000000
max        2508.000000
Name: Bottles Sold, dtype: float64

Column Sale (Dollars)
count      270955
unique       6580
top       $162.00
freq         3482
Name: Sale (Dollars), dtype: object

Column Volume Sold (Liters)
count    270955.000000
mean          8.981351
std          28.913690
min           0.100000
25%           1.500000
50%           5.250000
75%          10.500000
max        2508.000000
Name: Volume Sold (Liters), dtype: float64

Column Volume Sold (Gallons)
count    270955.000000
mean          2.372830
std           7.638182
min           0.030000
25%           0.400000
50%           1.390000
75%           2.770000
max         662.540000
Name: Volume Sold (Gallons), dtype: float64

Index([u'Date', u'Store Number', u'City', u'Zip Code', u'County Number',
       u'County', u'Category', u'Category Name', u'Vendor Number',
       u'Item Number', u'Item Description', u'Bottle Volume (ml)',
       u'State Bottle Cost', u'State Bottle Retail', u'Bottles Sold',
       u'Sale (Dollars)', u'Volume Sold (Liters)', u'Volume Sold (Gallons)'],
      dtype='object')
Date                     datetime64[ns]
Store Number                      int64
City                             object
Zip Code                         object
County Number                   float64
County                           object
Category                        float64
Category Name                    object
Vendor Number                     int64
Item Number                       int64
Item Description                 object
Bottle Volume (ml)                int64
State Bottle Cost                object
State Bottle Retail              object
Bottles Sold                      int64
Sale (Dollars)                   object
Volume Sold (Liters)            float64
Volume Sold (Gallons)           float64
dtype: object

In [362]:
def clean_based_on_known(master_field, nan_field, nan_partner_field):
    print df[df[nan_field].isnull()][[master_field,nan_partner_field,nan_field]].drop_duplicates()
    print
    print
    df_nan = df[df[nan_field].isnull()][[master_field]].drop_duplicates()
    for x in df_nan[master_field]:
        use_this = df[(df[master_field]==x)&(df[nan_partner_field].notnull())]\
        [[master_field,nan_partner_field,nan_field]].drop_duplicates()
        row_count = len(use_this.index)
        print row_count
        print
        if row_count == 1: 
            search_city = use_this[master_field].to_frame().iloc[0,0]
            print search_city 
            df.loc[df[master_field] == search_city, nan_field] = use_this[nan_field].to_frame().iloc[0,0]
            df.loc[df[master_field] == search_city, nan_partner_field] = use_this[nan_partner_field].to_frame().iloc[0,0]
    print "NULL nan_field:", nan_field, df[df[nan_field].isnull()][[master_field,nan_partner_field,nan_field]].drop_duplicates()
    print
    print "NULL nan_partner_field:",nan_partner_field,df[df[nan_partner_field].isnull()][[master_field,nan_partner_field,nan_field]].drop_duplicates()
    print 
    print

#clean_based_on_known('Store Number', "County", 'County Number')
#clean_based_on_known('Store Number', "County Number", 'County')
#clean_based_on_known('Item Description', "Category", 'Category Name')
clean_based_on_known('Item Description', "Category Name", 'Category')
#clean_based_on_known('Zip Code', "County Number", 'County')


df.loc[df['Zip Code'] == '51632', 'County'] = 'Page'
df.loc[df['Zip Code'] == '51632', 'County Number'] = '73'
df.loc[df['Zip Code'] == '52317', 'County'] = 'Johnson'
df.loc[df['Zip Code'] == '52317', 'County Number'] = '52'
df.loc[df['Zip Code'] == '50601', 'County'] = 'Hardin'
df.loc[df['Zip Code'] == '50601', 'County Number'] = '42'
df.loc[df['Zip Code'] == '51653', 'County'] = 'Fremont'
df.loc[df['Zip Code'] == '51653', 'County Number'] = '36'
df.loc[df['Zip Code'] == '52590', 'County'] = 'Wayne'
df.loc[df['Zip Code'] == '52590', 'County Number'] = '93'
df.loc[df['Zip Code'] == '50237', 'County'] = 'Polk'
df.loc[df['Zip Code'] == '50237', 'County Number'] = '77'
df.loc[df['Zip Code'] == '50501', 'County'] = 'Webster'
df.loc[df['Zip Code'] == '50501', 'County Number'] = '94'

df.loc[df['City'] == 'CORNING', 'County Number'] = '2'
df.loc[df['City'] == 'CORNING', 'County'] = 'Adams'
df.loc[df['City'] == 'CORNING', 'Zip Code'] = '50841'

df.loc[df['City'] == 'DUNLAP', 'Zip Code'] = '51529'

                                         Item Description   Category  \
896                          Herradura Gold Reposado 6pak  1022200.0
901                                           Hennessy VS  1052100.0
1514                        Grand Marnier Raspberry Peach  1082100.0
1684                                   Hennessy Vs Cognac  1052100.0
2203                                         Svedka Vodka  1032100.0
2894                                   Disaronno Amaretto  1082100.0
4989                         Tim Smith's Climax Moonshine  1091100.0
6744    Jack Daniels TN Honey & Jack Daniels TN Fire 7...        NaN
10629                              Captain Morgan Coconut  1062500.0
11241                               Evan Williams Egg Nog        NaN
12230                          Grand Marnier Cordon Rouge  1082100.0
12774                          Ole Smoky Cherry Moonshine  1091300.0
12984                       Dr. McGillicuddy's Peach Mini  1082200.0
13803                                    Galliano Liqueur  1082100.0
17213                                      Exotico Blanco  1022200.0
21707                                         1800 Silver  1022200.0
22809                                      Hennessy Black  1052100.0
23180                            Hennessy Vs Cognac 100ml  1052100.0
26234                           Captain Morgan Grapefruit  1062500.0
26918                             Tres Generaciones Anejo  1022200.0
27020             Stolichnaya Premium Vodka 80 Proof (lv)  1032100.0
29798                             Bombay Sapphire w/Glass        NaN
30058                    Three Olives Cake Flavored Vodka  1032100.0
31086                            Captain Morgan Pineapple  1062500.0
31251                                Gosling's Black Seal  1062500.0
32221                              Blue Chair Bay Coconut  1062500.0
33724                                            Licor 43  1082100.0
35086                                  Rondiaz Rum Spiced  1062400.0
38188                    Stolichnaya Premium Vodka 80 Prf  1032100.0
39441                               Olmeca Altos Reposado  1022200.0
...                                                   ...        ...
51527                                      Leblon Cachaca  1092100.0
55347                 Woodford Reserve MC 1838 White Corn        NaN
58185                            Dr. McGillicuddy's Peach  1082200.0
59896                      Rothman & Winter Orchard Peach        NaN
63481                           La Collection Santa Claus  1032100.0
74864                    Stolichnaya Russian Vodka 80 Prf  1032100.0
79685                         Captain Morgan Coconut Mini  1062500.0
82402                              Il Tramonto Limoncello  1082100.0
83314                               Blue Chair Bay Banana  1062500.0
90410                                    Remy Martin VSOP  1052100.0
91484                Rondiaz Rum Spiced Black Cherry Mini  1062500.0
91606                         Glenfiddich 1963 Replica HA        NaN
91837                                         Ricura Mini  1082100.0
98880         Parkers Heritage Collection Malt Whiskey HA        NaN
99045                               Absolut w/Ginger Beer  1032100.0
100333                                   High Stick Vodka  1032100.0
104369                                     Passoa Liqueur  1082100.0
105372                                       Ciroc Ten HA  1032100.0
125044                                    Belvedere Vodka  1032100.0
130794                       Belvedere Intense Unfiltered  1032100.0
134489                                             Svedka  1032100.0
139160                      Captain Morgan Pineapple Mini  1062500.0
142979                     Knob Creek w/ Crystal Decanter        NaN
191577  Giffard Creme de Pamplemousse Rose Pink Grapef...  1082100.0
193087                                Casa Noble Reposado  1022200.0
193170                                   Peligroso Silver  1022200.0
197628                                       Rondiaz Mini  1062400.0
221808                            Courvoisier Vsop Cognac  1052100.0
252314                  American Born Moonshine Apple Pie  1011700.0
266646                                      Pearl Caramel  1091100.0

       Category Name
896              NaN
901              NaN
1514             NaN
1684             NaN
2203             NaN
2894             NaN
4989             NaN
6744             NaN
10629            NaN
11241            NaN
12230            NaN
12774            NaN
12984            NaN
13803            NaN
17213            NaN
21707            NaN
22809            NaN
23180            NaN
26234            NaN
26918            NaN
27020            NaN
29798            NaN
30058            NaN
31086            NaN
31251            NaN
32221            NaN
33724            NaN
35086            NaN
38188            NaN
39441            NaN
...              ...
51527            NaN
55347            NaN
58185            NaN
59896            NaN
63481            NaN
74864            NaN
79685            NaN
82402            NaN
83314            NaN
90410            NaN
91484            NaN
91606            NaN
91837            NaN
98880            NaN
99045            NaN
100333           NaN
104369           NaN
105372           NaN
125044           NaN
130794           NaN
134489           NaN
139160           NaN
142979           NaN
191577           NaN
193087           NaN
193170           NaN
197628           NaN
221808           NaN
252314           NaN
266646           NaN

[70 rows x 3 columns]


2

2

2

2

2

4

2

0

2

0

2

2

2

2

2

2

2

2

2

2

2

0

2

2

2

3

2

2

2

2

3

2

2

3

0

2

3

2

0

3

2

0

2

0

2

2

2

2

3

2

2

0

2

0

1

Absolut w/Ginger Beer
1

High Stick Vodka
2

1

Ciroc Ten HA
2

2

2

2

0

1

Giffard Creme de Pamplemousse Rose Pink Grapefruit Liqueur
2

2

2

2

2

1

Pearl Caramel
NULL nan_field: Category Name                                          Item Description   Category  \
896                          Herradura Gold Reposado 6pak  1022200.0
901                                           Hennessy VS  1052100.0
1514                        Grand Marnier Raspberry Peach  1082100.0
1684                                   Hennessy Vs Cognac  1052100.0
2203                                         Svedka Vodka  1032100.0
2894                                   Disaronno Amaretto  1082100.0
4989                         Tim Smith's Climax Moonshine  1091100.0
6744    Jack Daniels TN Honey & Jack Daniels TN Fire 7...        NaN
10629                              Captain Morgan Coconut  1062500.0
11241                               Evan Williams Egg Nog        NaN
12230                          Grand Marnier Cordon Rouge  1082100.0
12774                          Ole Smoky Cherry Moonshine  1091300.0
12984                       Dr. McGillicuddy's Peach Mini  1082200.0
13803                                    Galliano Liqueur  1082100.0
17213                                      Exotico Blanco  1022200.0
21707                                         1800 Silver  1022200.0
22809                                      Hennessy Black  1052100.0
23180                            Hennessy Vs Cognac 100ml  1052100.0
26234                           Captain Morgan Grapefruit  1062500.0
26918                             Tres Generaciones Anejo  1022200.0
27020             Stolichnaya Premium Vodka 80 Proof (lv)  1032100.0
29798                             Bombay Sapphire w/Glass        NaN
30058                    Three Olives Cake Flavored Vodka  1032100.0
31086                            Captain Morgan Pineapple  1062500.0
31251                                Gosling's Black Seal  1062500.0
32221                              Blue Chair Bay Coconut  1062500.0
33724                                            Licor 43  1082100.0
35086                                  Rondiaz Rum Spiced  1062400.0
38188                    Stolichnaya Premium Vodka 80 Prf  1032100.0
39441                               Olmeca Altos Reposado  1022200.0
...                                                   ...        ...
51527                                      Leblon Cachaca  1092100.0
55347                 Woodford Reserve MC 1838 White Corn        NaN
58185                            Dr. McGillicuddy's Peach  1082200.0
59896                      Rothman & Winter Orchard Peach        NaN
63481                           La Collection Santa Claus  1032100.0
74864                    Stolichnaya Russian Vodka 80 Prf  1032100.0
79685                         Captain Morgan Coconut Mini  1062500.0
82402                              Il Tramonto Limoncello  1082100.0
83314                               Blue Chair Bay Banana  1062500.0
90410                                    Remy Martin VSOP  1052100.0
91484                Rondiaz Rum Spiced Black Cherry Mini  1062500.0
91606                         Glenfiddich 1963 Replica HA        NaN
91837                                         Ricura Mini  1082100.0
98880         Parkers Heritage Collection Malt Whiskey HA        NaN
99045                               Absolut w/Ginger Beer  1032100.0
100333                                   High Stick Vodka  1032100.0
104369                                     Passoa Liqueur  1082100.0
105372                                       Ciroc Ten HA  1032100.0
125044                                    Belvedere Vodka  1032100.0
130794                       Belvedere Intense Unfiltered  1032100.0
134489                                             Svedka  1032100.0
139160                      Captain Morgan Pineapple Mini  1062500.0
142979                     Knob Creek w/ Crystal Decanter        NaN
191577  Giffard Creme de Pamplemousse Rose Pink Grapef...  1082100.0
193087                                Casa Noble Reposado  1022200.0
193170                                   Peligroso Silver  1022200.0
197628                                       Rondiaz Mini  1062400.0
221808                            Courvoisier Vsop Cognac  1052100.0
252314                  American Born Moonshine Apple Pie  1011700.0
266646                                      Pearl Caramel  1091100.0

       Category Name
896              NaN
901              NaN
1514             NaN
1684             NaN
2203             NaN
2894             NaN
4989             NaN
6744             NaN
10629            NaN
11241            NaN
12230            NaN
12774            NaN
12984            NaN
13803            NaN
17213            NaN
21707            NaN
22809            NaN
23180            NaN
26234            NaN
26918            NaN
27020            NaN
29798            NaN
30058            NaN
31086            NaN
31251            NaN
32221            NaN
33724            NaN
35086            NaN
38188            NaN
39441            NaN
...              ...
51527            NaN
55347            NaN
58185            NaN
59896            NaN
63481            NaN
74864            NaN
79685            NaN
82402            NaN
83314            NaN
90410            NaN
91484            NaN
91606            NaN
91837            NaN
98880            NaN
99045            NaN
100333           NaN
104369           NaN
105372           NaN
125044           NaN
130794           NaN
134489           NaN
139160           NaN
142979           NaN
191577           NaN
193087           NaN
193170           NaN
197628           NaN
221808           NaN
252314           NaN
266646           NaN

[70 rows x 3 columns]

NULL nan_partner_field: Category                                          Item Description  Category  \
6744    Jack Daniels TN Honey & Jack Daniels TN Fire 7...       NaN
11241                               Evan Williams Egg Nog       NaN
29798                             Bombay Sapphire w/Glass       NaN
44595                      Pinnacle Candy Cane Trial Pack       NaN
48348                 Wild Turkey American Honey Shot Tap       NaN
55347                 Woodford Reserve MC 1838 White Corn       NaN
59896                      Rothman & Winter Orchard Peach       NaN
91606                         Glenfiddich 1963 Replica HA       NaN
98880         Parkers Heritage Collection Malt Whiskey HA       NaN
142979                     Knob Creek w/ Crystal Decanter       NaN

       Category Name
6744             NaN
11241            NaN
29798            NaN
44595            NaN
48348            NaN
55347            NaN
59896            NaN
91606            NaN
98880            NaN
142979           NaN

In [360]:
df[df['City']=='CEDAR RAPIDS'][['City','County Number','County']].drop_duplicates()
df.loc[df['City'] == 'CEDAR RAPIDS', 'County'] = 'Linn'
df.loc[df['City'] == 'CEDAR RAPIDS', 'County Number'] = '57'
df[df['City']=='CEDAR RAPIDS'][['City','County Number','County']].drop_duplicates()
df[df['County'].isnull()][['City','County Number','County']].drop_duplicates()

Empty DataFrame
Columns: [City, County Number, County]
Index: []

In [361]:
## df[df['City'].isnull()][['City']].drop_duplicates()
df[df['Category Name'].isnull()][['Category','Category Name', 'Item Description']].drop_duplicates()
df[df['Item Description'] == 'Herradura Gold Reposado 6pak'][['Category','Category Name', 'Item Description']].drop_duplicates()
#df[df['County']=='Polk'][['Zip Code','City','County Number','County']].drop_duplicates()
#df[df['City']=='CORNING'][['Zip Code','City','County Number','County']].drop_duplicates()
#df['County Number'] = df['County Number'].astype(int)
#df['Category'] = df['Category'].astype(int)

#df.dtypes

       Category Category Name              Item Description
896   1022200.0           NaN  Herradura Gold Reposado 6pak
5928  1022100.0       TEQUILA  Herradura Gold Reposado 6pak

In [285]:
print df[df['County'].isnull()][['City','County Number','County']].drop_duplicates()

Empty DataFrame
Columns: [City, County Number, County]
Index: []

# Explore the data

Perform some exploratory statistical analysis and make some plots, such as histograms of transaction totals, bottles sold, etc.

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

## Record your findings

Be sure to write out anything observations from your exploratory analysis.

# Mine the data
Now you are ready to compute the variables you will use for your regression from the data. For example, you may want to
compute total sales per store from Jan to March of 2015, mean price per bottle, etc. Refer to the readme for more ideas appropriate to your scenario.

Pandas is your friend for this task. Take a look at the operations [here](http://pandas.pydata.org/pandas-docs/stable/groupby.html) for ideas on how to make the best use of pandas and feel free to search for blog and Stack Overflow posts to help you group data by certain variables and compute sums, means, etc. You may find it useful to create a new data frame to house this summary data.

# Refine the data
Look for any statistical relationships, correlations, or other relevant properties of the dataset.

# Build your models

Using scikit-learn or statsmodels, build the necessary models for your scenario. Evaluate model fit.

In [6]:
from sklearn import linear_model

## Plot your results

Again make sure that you record any valuable information. For example, in the tax scenario, did you find the sales from the first three months of the year to be a good predictor of the total sales for the year? Plot the predictions versus the true values and discuss the successes and limitations of your models

# Present the Results

Present your conclusions and results. If you have more than one interesting model feel free to include more than one along with a discussion. Use your work in this notebook to prepare your write-up.